### ISSUE TITLE
Modular-Series missing

### ISSUE THREAD

**Issue by nayanishuklaGIT** [nayanishuklaGIT/Nakamura-Software#1]
Modular-Series missing in the 841_Div 2

**Comment by whynesspower** [comment]
Please approve the issue to me

**Comment by nayanishuklaGIT** [comment]
Issue assigned to @whynesspower Thanks

**Comment by whynesspower** [comment]
Kindly merge the PR!

**Comment by nayanishuklaGIT** [comment]
Issue solved! Thanks @whynesspower
